[package]
name = "lancedb-pinvoke"
version = "0.0.1"
description = "P/Invoke for LanceDB"
rust-version = "1.80.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lancedb = "0.12.0"
tokio = { version = "1", features = ["full"] }
lazy_static = "1.5.0"
libc = "0.2"

